version: '3.8'

services:
  # Django application service
  django:
    build: .
    volumes:
      - .:/app  # Mount your Django app directory as a volume
    ports:
      - "8000:8000"  # Map container port 8000 to host port 8000
    environment:
      # Set environment variables for database connection details
      POSTGRES_HOST: postgres
      POSTGRES_USER: postgres  # Replace if using a different username
      POSTGRES_PASSWORD: password  # Replace with your actual password
      POSTGRES_DB: task_manager  # Replace with your database name

  # Postgres database service (optional)
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: password  # Set an environment variable for the password
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Persistent storage for Postgres data

volumes:
  postgres_data: {}