version: '3.8'

services:
  # Django application service
  django:
    build: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      # Set environment variables for database connection details
      POSTGRES_HOST: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: task_manager

  # Postgres database service
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Redis service
  redis:
    image: redis:latest
    volumes:
      - redis_data:/data

  # Celery Beat service
  celery-beat:
    build: .
    command: celery -A task_manager beat -l info
    depends_on:
      - redis

  # Celery Worker service (multiple processes)
  celery-worker:
    build: .
    command: celery -A task_manager worker -l info -c 2
    depends_on:
      - redis
      - django
      - postgres

volumes:
  postgres_data: {}
  redis_data: {}